# -*- coding: utf-8 -*-
"""iris_flower_classification.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gqbl7BLUFrL8qYmNLY05QVXUCp0_VFnx

#### **Step 1: Upload the Dataset to Colab**
Upload your Iris.csv file into Google Colab:
1. Click the Folder icon 📁 on the left sidebar menu of Colab.
2. Click the Upload icon 📄 (paper icon with an up arrow).
3. Select your Iris.csv file from your computer and upload it.

#### **Step 2: Import Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

"""#### **Step 3: Load Data and Drop Unnecessary Columns**"""

# Load the uploaded file from the Colab storage
df = pd.read_csv('Iris.csv')

# Drop the 'Id' column if it exists in your dataset to avoid messing up training
if 'Id' in df.columns:
    df = df.drop(columns=['Id'])

df = df.dropna()

# Display the first 5 rows to verify the column names
print("Dataset successfully initialized from Iris.csv!")
df.head()

"""#### **Step 4: Explore Feature Relationships (Visual Output 1)**"""

# Detect whatever label column holds your target species categories
species_col = 'Species' if 'Species' in df.columns else 'species'

# VISUAL OUTPUT 1: Pairplot matrix
sns.pairplot(df, hue=species_col, palette='Set1', diag_kind='kde')
plt.suptitle('Iris Flower Feature Distribution and Clustering', y=1.02, fontsize=14, fontweight='bold')
plt.show()

"""#### **Step 5: Separate Variables and Split Data**"""

# Separate features (X) from the target category (y)
X = df.drop(columns=[species_col])
y = df[species_col]

# Split into 80% training data and 20% validation data sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Scale features so columns are normalized on the same comparative level
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""#### **Step 6: Train the Classifier Model**"""

# Initialize and fit the machine learning algorithm
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train_scaled, y_train)

print("Model training successfully completed!")

"""#### **Step 7: Evaluate Validation Metrics**"""

# Predict species classifications on validation rows
y_pred = model.predict(X_test_scaled)

# Print accuracy verification scoring margins
accuracy = accuracy_score(y_test, y_pred)
print(f"Overall Classification Accuracy Score: {accuracy*100:.2f}%\n")

print("--- Granular Performance Matrix Report ---")
print(classification_report(y_test, y_pred))

"""#### **Step 8: Render a Confusion Matrix Heatmap (Visual Output 2)**"""

# Calculate error cross-checks
cm = confusion_matrix(y_test, y_pred)
unique_labels = sorted(y.unique())

# VISUAL OUTPUT 2: Confusion Matrix Heatmap
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Purples',
            xticklabels=unique_labels, yticklabels=unique_labels)
plt.title('Classification Error Matrix (Confusion Matrix)', fontsize=12, fontweight='bold', pad=15)
plt.xlabel('Predicted Species Label')
plt.ylabel('Actual Species Label')
plt.show()